// flow-typed signature: e39a6e1a54352bec7457d0a3f85f03c2
// flow-typed version: <<STUB>>/flow-jsdoc_v^0.3.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'flow-jsdoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'flow-jsdoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'flow-jsdoc/app' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/lib/falafel' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/01-object-literal' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/02-es6-class' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/03-stand-alone-function' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/04-function-as-var' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/05-prototype-class' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/06-nested-functions' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/07-es6-class-field-decls' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/08-inline-syntax' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/09-jsx' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/10-es6-fat-arrows' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/11-optional-params' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/expected_output/12-es6-export-function' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/01-object-literal' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/02-es6-class' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/03-stand-alone-function' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/04-function-as-var' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/05-prototype-class' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/06-nested-functions' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/07-es6-class-field-decls' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/08-inline-syntax' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/09-jsx' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/10-es6-fat-arrows' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/11-optional-params' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/input/12-es6-export-function' {
  declare module.exports: any;
}

declare module 'flow-jsdoc/tests/runner' {
  declare module.exports: any;
}

// Filename aliases
declare module 'flow-jsdoc/app.js' {
  declare module.exports: $Exports<'flow-jsdoc/app'>;
}
declare module 'flow-jsdoc/index' {
  declare module.exports: $Exports<'flow-jsdoc'>;
}
declare module 'flow-jsdoc/index.js' {
  declare module.exports: $Exports<'flow-jsdoc'>;
}
declare module 'flow-jsdoc/lib/falafel.js' {
  declare module.exports: $Exports<'flow-jsdoc/lib/falafel'>;
}
declare module 'flow-jsdoc/tests/expected_output/01-object-literal.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/01-object-literal'>;
}
declare module 'flow-jsdoc/tests/expected_output/02-es6-class.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/02-es6-class'>;
}
declare module 'flow-jsdoc/tests/expected_output/03-stand-alone-function.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/03-stand-alone-function'>;
}
declare module 'flow-jsdoc/tests/expected_output/04-function-as-var.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/04-function-as-var'>;
}
declare module 'flow-jsdoc/tests/expected_output/05-prototype-class.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/05-prototype-class'>;
}
declare module 'flow-jsdoc/tests/expected_output/06-nested-functions.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/06-nested-functions'>;
}
declare module 'flow-jsdoc/tests/expected_output/07-es6-class-field-decls.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/07-es6-class-field-decls'>;
}
declare module 'flow-jsdoc/tests/expected_output/08-inline-syntax.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/08-inline-syntax'>;
}
declare module 'flow-jsdoc/tests/expected_output/09-jsx.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/09-jsx'>;
}
declare module 'flow-jsdoc/tests/expected_output/10-es6-fat-arrows.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/10-es6-fat-arrows'>;
}
declare module 'flow-jsdoc/tests/expected_output/11-optional-params.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/11-optional-params'>;
}
declare module 'flow-jsdoc/tests/expected_output/12-es6-export-function.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/expected_output/12-es6-export-function'>;
}
declare module 'flow-jsdoc/tests/input/01-object-literal.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/01-object-literal'>;
}
declare module 'flow-jsdoc/tests/input/02-es6-class.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/02-es6-class'>;
}
declare module 'flow-jsdoc/tests/input/03-stand-alone-function.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/03-stand-alone-function'>;
}
declare module 'flow-jsdoc/tests/input/04-function-as-var.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/04-function-as-var'>;
}
declare module 'flow-jsdoc/tests/input/05-prototype-class.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/05-prototype-class'>;
}
declare module 'flow-jsdoc/tests/input/06-nested-functions.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/06-nested-functions'>;
}
declare module 'flow-jsdoc/tests/input/07-es6-class-field-decls.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/07-es6-class-field-decls'>;
}
declare module 'flow-jsdoc/tests/input/08-inline-syntax.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/08-inline-syntax'>;
}
declare module 'flow-jsdoc/tests/input/09-jsx.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/09-jsx'>;
}
declare module 'flow-jsdoc/tests/input/10-es6-fat-arrows.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/10-es6-fat-arrows'>;
}
declare module 'flow-jsdoc/tests/input/11-optional-params.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/11-optional-params'>;
}
declare module 'flow-jsdoc/tests/input/12-es6-export-function.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/input/12-es6-export-function'>;
}
declare module 'flow-jsdoc/tests/runner.js' {
  declare module.exports: $Exports<'flow-jsdoc/tests/runner'>;
}
