// flow-typed signature: 7e558a70cdf78716e608a7cbcd250df1
// flow-typed version: <<STUB>>/google-datastore-emulator_v^1.0.5/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'google-datastore-emulator'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'google-datastore-emulator' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'google-datastore-emulator/src/datastore-emulator' {
  declare module.exports: any;
}

declare module 'google-datastore-emulator/src/emulator-states' {
  declare module.exports: any;
}

declare module 'google-datastore-emulator/test/datastore.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'google-datastore-emulator/index' {
  declare module.exports: $Exports<'google-datastore-emulator'>;
}
declare module 'google-datastore-emulator/index.js' {
  declare module.exports: $Exports<'google-datastore-emulator'>;
}
declare module 'google-datastore-emulator/src/datastore-emulator.js' {
  declare module.exports: $Exports<'google-datastore-emulator/src/datastore-emulator'>;
}
declare module 'google-datastore-emulator/src/emulator-states.js' {
  declare module.exports: $Exports<'google-datastore-emulator/src/emulator-states'>;
}
declare module 'google-datastore-emulator/test/datastore.spec.js' {
  declare module.exports: $Exports<'google-datastore-emulator/test/datastore.spec'>;
}
