// flow-typed signature: 58ab1975dd3160d1dbdb64e8a9ecd7bf
// flow-typed version: <<STUB>>/gulp-copy_v^1.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-copy'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-copy' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'gulp-copy/example/gulpfile' {
  declare module.exports: any;
}

declare module 'gulp-copy/lib/gulp-copy' {
  declare module.exports: any;
}

declare module 'gulp-copy/test/spec/gulp-copy.spec' {
  declare module.exports: any;
}

// Filename aliases
declare module 'gulp-copy/example/gulpfile.js' {
  declare module.exports: $Exports<'gulp-copy/example/gulpfile'>;
}
declare module 'gulp-copy/index' {
  declare module.exports: $Exports<'gulp-copy'>;
}
declare module 'gulp-copy/index.js' {
  declare module.exports: $Exports<'gulp-copy'>;
}
declare module 'gulp-copy/lib/gulp-copy.js' {
  declare module.exports: $Exports<'gulp-copy/lib/gulp-copy'>;
}
declare module 'gulp-copy/test/spec/gulp-copy.spec.js' {
  declare module.exports: $Exports<'gulp-copy/test/spec/gulp-copy.spec'>;
}
