// flow-typed signature: 6a7cc9f675fe887f92a069790885e2f1
// flow-typed version: <<STUB>>/gulp-exec_v^2.1.3/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'gulp-exec'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'gulp-exec' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'gulp-exec/index' {
  declare module.exports: $Exports<'gulp-exec'>;
}
declare module 'gulp-exec/index.js' {
  declare module.exports: $Exports<'gulp-exec'>;
}
