// flow-typed signature: 7110b0beb8ee08de055d7a4830a8510b
// flow-typed version: <<STUB>>/http-compose_v^1.0.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-compose'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-compose' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-compose/example' {
  declare module.exports: any;
}

declare module 'http-compose/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-compose/example.js' {
  declare module.exports: $Exports<'http-compose/example'>;
}
declare module 'http-compose/index' {
  declare module.exports: $Exports<'http-compose'>;
}
declare module 'http-compose/index.js' {
  declare module.exports: $Exports<'http-compose'>;
}
declare module 'http-compose/test/index.js' {
  declare module.exports: $Exports<'http-compose/test/index'>;
}
