// flow-typed signature: c0269c7eb9395b28b6286ed47d46e3eb
// flow-typed version: <<STUB>>/http-sender_v^2.0.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'http-sender'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'http-sender' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'http-sender/example' {
  declare module.exports: any;
}

declare module 'http-sender/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'http-sender/example.js' {
  declare module.exports: $Exports<'http-sender/example'>;
}
declare module 'http-sender/index' {
  declare module.exports: $Exports<'http-sender'>;
}
declare module 'http-sender/index.js' {
  declare module.exports: $Exports<'http-sender'>;
}
declare module 'http-sender/test/index.js' {
  declare module.exports: $Exports<'http-sender/test/index'>;
}
