// flow-typed signature: 336ec5c2bffeba66b5d41d0575915160
// flow-typed version: <<STUB>>/intelli-espower-loader_v^1.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'intelli-espower-loader'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'intelli-espower-loader' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'intelli-espower-loader/example/test/fail-test' {
  declare module.exports: any;
}

declare module 'intelli-espower-loader/example/test/pass-test' {
  declare module.exports: any;
}

declare module 'intelli-espower-loader/intelli-espower-loader' {
  declare module.exports: any;
}

declare module 'intelli-espower-loader/lib/get-package-json' {
  declare module.exports: any;
}

declare module 'intelli-espower-loader/lib/get-test-dir' {
  declare module.exports: any;
}

declare module 'intelli-espower-loader/lib/normalize-dir' {
  declare module.exports: any;
}

declare module 'intelli-espower-loader/test/get-test-dir-test' {
  declare module.exports: any;
}

declare module 'intelli-espower-loader/test/normalize-dir-test' {
  declare module.exports: any;
}

// Filename aliases
declare module 'intelli-espower-loader/example/test/fail-test.js' {
  declare module.exports: $Exports<'intelli-espower-loader/example/test/fail-test'>;
}
declare module 'intelli-espower-loader/example/test/pass-test.js' {
  declare module.exports: $Exports<'intelli-espower-loader/example/test/pass-test'>;
}
declare module 'intelli-espower-loader/intelli-espower-loader.js' {
  declare module.exports: $Exports<'intelli-espower-loader/intelli-espower-loader'>;
}
declare module 'intelli-espower-loader/lib/get-package-json.js' {
  declare module.exports: $Exports<'intelli-espower-loader/lib/get-package-json'>;
}
declare module 'intelli-espower-loader/lib/get-test-dir.js' {
  declare module.exports: $Exports<'intelli-espower-loader/lib/get-test-dir'>;
}
declare module 'intelli-espower-loader/lib/normalize-dir.js' {
  declare module.exports: $Exports<'intelli-espower-loader/lib/normalize-dir'>;
}
declare module 'intelli-espower-loader/test/get-test-dir-test.js' {
  declare module.exports: $Exports<'intelli-espower-loader/test/get-test-dir-test'>;
}
declare module 'intelli-espower-loader/test/normalize-dir-test.js' {
  declare module.exports: $Exports<'intelli-espower-loader/test/normalize-dir-test'>;
}
