// flow-typed signature: 5d466425f252cdf8f3806eed4b8eda5f
// flow-typed version: <<STUB>>/is-array_v^1.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'is-array'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'is-array' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'is-array/index' {
  declare module.exports: $Exports<'is-array'>;
}
declare module 'is-array/index.js' {
  declare module.exports: $Exports<'is-array'>;
}
