// flow-typed signature: bcc7ffd18f02e37e61621233071269a6
// flow-typed version: <<STUB>>/level-party_v^3.0.4/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'level-party'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'level-party' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'level-party/example/bulk-insert' {
  declare module.exports: any;
}

declare module 'level-party/example/get' {
  declare module.exports: any;
}

declare module 'level-party/example/put' {
  declare module.exports: any;
}

declare module 'level-party/example/read-stream' {
  declare module.exports: any;
}

declare module 'level-party/test/bytewise_sublevel' {
  declare module.exports: any;
}

declare module 'level-party/test/bytewise' {
  declare module.exports: any;
}

declare module 'level-party/test/election' {
  declare module.exports: any;
}

declare module 'level-party/test/handle' {
  declare module.exports: any;
}

declare module 'level-party/test/sublevel' {
  declare module.exports: any;
}

// Filename aliases
declare module 'level-party/example/bulk-insert.js' {
  declare module.exports: $Exports<'level-party/example/bulk-insert'>;
}
declare module 'level-party/example/get.js' {
  declare module.exports: $Exports<'level-party/example/get'>;
}
declare module 'level-party/example/put.js' {
  declare module.exports: $Exports<'level-party/example/put'>;
}
declare module 'level-party/example/read-stream.js' {
  declare module.exports: $Exports<'level-party/example/read-stream'>;
}
declare module 'level-party/index' {
  declare module.exports: $Exports<'level-party'>;
}
declare module 'level-party/index.js' {
  declare module.exports: $Exports<'level-party'>;
}
declare module 'level-party/test/bytewise_sublevel.js' {
  declare module.exports: $Exports<'level-party/test/bytewise_sublevel'>;
}
declare module 'level-party/test/bytewise.js' {
  declare module.exports: $Exports<'level-party/test/bytewise'>;
}
declare module 'level-party/test/election.js' {
  declare module.exports: $Exports<'level-party/test/election'>;
}
declare module 'level-party/test/handle.js' {
  declare module.exports: $Exports<'level-party/test/handle'>;
}
declare module 'level-party/test/sublevel.js' {
  declare module.exports: $Exports<'level-party/test/sublevel'>;
}
