// flow-typed signature: 60ebe6dbd86a54e5efb55e59f64483aa
// flow-typed version: <<STUB>>/level-sublevel_v^6.6.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'level-sublevel'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'level-sublevel' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'level-sublevel/_test/batch' {
  declare module.exports: any;
}

declare module 'level-sublevel/_test/hook' {
  declare module.exports: any;
}

declare module 'level-sublevel/_test/limit' {
  declare module.exports: any;
}

declare module 'level-sublevel/_test/mixed-value-encodings-per-action-del' {
  declare module.exports: any;
}

declare module 'level-sublevel/_test/mixed-value-encodings-per-sub-del' {
  declare module.exports: any;
}

declare module 'level-sublevel/_test/mixed-value-encodings-writeStream-per-sub' {
  declare module.exports: any;
}

declare module 'level-sublevel/_test/mixed-value-encodings-writeStream-per-write' {
  declare module.exports: any;
}

declare module 'level-sublevel/_test/posthook-ranges' {
  declare module.exports: any;
}

declare module 'level-sublevel/_test/prehook-batch' {
  declare module.exports: any;
}

declare module 'level-sublevel/_test/prehook-insert' {
  declare module.exports: any;
}

declare module 'level-sublevel/batch' {
  declare module.exports: any;
}

declare module 'level-sublevel/bytewise' {
  declare module.exports: any;
}

declare module 'level-sublevel/codec/bytewise' {
  declare module.exports: any;
}

declare module 'level-sublevel/codec/index' {
  declare module.exports: any;
}

declare module 'level-sublevel/codec/legacy' {
  declare module.exports: any;
}

declare module 'level-sublevel/examples/queue' {
  declare module.exports: any;
}

declare module 'level-sublevel/examples/trigger' {
  declare module.exports: any;
}

declare module 'level-sublevel/hooks' {
  declare module.exports: any;
}

declare module 'level-sublevel/legacy' {
  declare module.exports: any;
}

declare module 'level-sublevel/nut' {
  declare module.exports: any;
}

declare module 'level-sublevel/pull' {
  declare module.exports: any;
}

declare module 'level-sublevel/range' {
  declare module.exports: any;
}

declare module 'level-sublevel/shell' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/close' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/codec' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/errors' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/falsey-value' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/hooks' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/inherit-encodings' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/is-open' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/key-stream-issues' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/key-value-stream' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/keyvalue' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/legacy-apis' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/legacy-start-end' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/level' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/mixed-value-encodings-per-action' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/mixed-value-encodings-per-sub' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/mock' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/nested-prehooks' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/range' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/reverse-order' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/reverse' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/streams-sublevel-key-value' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/streams' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/sublevels' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/trigger' {
  declare module.exports: any;
}

declare module 'level-sublevel/test/version' {
  declare module.exports: any;
}

// Filename aliases
declare module 'level-sublevel/_test/batch.js' {
  declare module.exports: $Exports<'level-sublevel/_test/batch'>;
}
declare module 'level-sublevel/_test/hook.js' {
  declare module.exports: $Exports<'level-sublevel/_test/hook'>;
}
declare module 'level-sublevel/_test/limit.js' {
  declare module.exports: $Exports<'level-sublevel/_test/limit'>;
}
declare module 'level-sublevel/_test/mixed-value-encodings-per-action-del.js' {
  declare module.exports: $Exports<'level-sublevel/_test/mixed-value-encodings-per-action-del'>;
}
declare module 'level-sublevel/_test/mixed-value-encodings-per-sub-del.js' {
  declare module.exports: $Exports<'level-sublevel/_test/mixed-value-encodings-per-sub-del'>;
}
declare module 'level-sublevel/_test/mixed-value-encodings-writeStream-per-sub.js' {
  declare module.exports: $Exports<'level-sublevel/_test/mixed-value-encodings-writeStream-per-sub'>;
}
declare module 'level-sublevel/_test/mixed-value-encodings-writeStream-per-write.js' {
  declare module.exports: $Exports<'level-sublevel/_test/mixed-value-encodings-writeStream-per-write'>;
}
declare module 'level-sublevel/_test/posthook-ranges.js' {
  declare module.exports: $Exports<'level-sublevel/_test/posthook-ranges'>;
}
declare module 'level-sublevel/_test/prehook-batch.js' {
  declare module.exports: $Exports<'level-sublevel/_test/prehook-batch'>;
}
declare module 'level-sublevel/_test/prehook-insert.js' {
  declare module.exports: $Exports<'level-sublevel/_test/prehook-insert'>;
}
declare module 'level-sublevel/batch.js' {
  declare module.exports: $Exports<'level-sublevel/batch'>;
}
declare module 'level-sublevel/bytewise.js' {
  declare module.exports: $Exports<'level-sublevel/bytewise'>;
}
declare module 'level-sublevel/codec/bytewise.js' {
  declare module.exports: $Exports<'level-sublevel/codec/bytewise'>;
}
declare module 'level-sublevel/codec/index.js' {
  declare module.exports: $Exports<'level-sublevel/codec/index'>;
}
declare module 'level-sublevel/codec/legacy.js' {
  declare module.exports: $Exports<'level-sublevel/codec/legacy'>;
}
declare module 'level-sublevel/examples/queue.js' {
  declare module.exports: $Exports<'level-sublevel/examples/queue'>;
}
declare module 'level-sublevel/examples/trigger.js' {
  declare module.exports: $Exports<'level-sublevel/examples/trigger'>;
}
declare module 'level-sublevel/hooks.js' {
  declare module.exports: $Exports<'level-sublevel/hooks'>;
}
declare module 'level-sublevel/index' {
  declare module.exports: $Exports<'level-sublevel'>;
}
declare module 'level-sublevel/index.js' {
  declare module.exports: $Exports<'level-sublevel'>;
}
declare module 'level-sublevel/legacy.js' {
  declare module.exports: $Exports<'level-sublevel/legacy'>;
}
declare module 'level-sublevel/nut.js' {
  declare module.exports: $Exports<'level-sublevel/nut'>;
}
declare module 'level-sublevel/pull.js' {
  declare module.exports: $Exports<'level-sublevel/pull'>;
}
declare module 'level-sublevel/range.js' {
  declare module.exports: $Exports<'level-sublevel/range'>;
}
declare module 'level-sublevel/shell.js' {
  declare module.exports: $Exports<'level-sublevel/shell'>;
}
declare module 'level-sublevel/test/close.js' {
  declare module.exports: $Exports<'level-sublevel/test/close'>;
}
declare module 'level-sublevel/test/codec.js' {
  declare module.exports: $Exports<'level-sublevel/test/codec'>;
}
declare module 'level-sublevel/test/errors.js' {
  declare module.exports: $Exports<'level-sublevel/test/errors'>;
}
declare module 'level-sublevel/test/falsey-value.js' {
  declare module.exports: $Exports<'level-sublevel/test/falsey-value'>;
}
declare module 'level-sublevel/test/hooks.js' {
  declare module.exports: $Exports<'level-sublevel/test/hooks'>;
}
declare module 'level-sublevel/test/inherit-encodings.js' {
  declare module.exports: $Exports<'level-sublevel/test/inherit-encodings'>;
}
declare module 'level-sublevel/test/is-open.js' {
  declare module.exports: $Exports<'level-sublevel/test/is-open'>;
}
declare module 'level-sublevel/test/key-stream-issues.js' {
  declare module.exports: $Exports<'level-sublevel/test/key-stream-issues'>;
}
declare module 'level-sublevel/test/key-value-stream.js' {
  declare module.exports: $Exports<'level-sublevel/test/key-value-stream'>;
}
declare module 'level-sublevel/test/keyvalue.js' {
  declare module.exports: $Exports<'level-sublevel/test/keyvalue'>;
}
declare module 'level-sublevel/test/legacy-apis.js' {
  declare module.exports: $Exports<'level-sublevel/test/legacy-apis'>;
}
declare module 'level-sublevel/test/legacy-start-end.js' {
  declare module.exports: $Exports<'level-sublevel/test/legacy-start-end'>;
}
declare module 'level-sublevel/test/level.js' {
  declare module.exports: $Exports<'level-sublevel/test/level'>;
}
declare module 'level-sublevel/test/mixed-value-encodings-per-action.js' {
  declare module.exports: $Exports<'level-sublevel/test/mixed-value-encodings-per-action'>;
}
declare module 'level-sublevel/test/mixed-value-encodings-per-sub.js' {
  declare module.exports: $Exports<'level-sublevel/test/mixed-value-encodings-per-sub'>;
}
declare module 'level-sublevel/test/mock.js' {
  declare module.exports: $Exports<'level-sublevel/test/mock'>;
}
declare module 'level-sublevel/test/nested-prehooks.js' {
  declare module.exports: $Exports<'level-sublevel/test/nested-prehooks'>;
}
declare module 'level-sublevel/test/range.js' {
  declare module.exports: $Exports<'level-sublevel/test/range'>;
}
declare module 'level-sublevel/test/reverse-order.js' {
  declare module.exports: $Exports<'level-sublevel/test/reverse-order'>;
}
declare module 'level-sublevel/test/reverse.js' {
  declare module.exports: $Exports<'level-sublevel/test/reverse'>;
}
declare module 'level-sublevel/test/streams-sublevel-key-value.js' {
  declare module.exports: $Exports<'level-sublevel/test/streams-sublevel-key-value'>;
}
declare module 'level-sublevel/test/streams.js' {
  declare module.exports: $Exports<'level-sublevel/test/streams'>;
}
declare module 'level-sublevel/test/sublevels.js' {
  declare module.exports: $Exports<'level-sublevel/test/sublevels'>;
}
declare module 'level-sublevel/test/trigger.js' {
  declare module.exports: $Exports<'level-sublevel/test/trigger'>;
}
declare module 'level-sublevel/test/version.js' {
  declare module.exports: $Exports<'level-sublevel/test/version'>;
}
