// flow-typed signature: 59ce4b1210c6ed3ba14ed81255acab1b
// flow-typed version: <<STUB>>/npm-run_v^4.1.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'npm-run'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'npm-run' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'npm-run/bin/npm-run' {
  declare module.exports: any;
}

declare module 'npm-run/test/bin' {
  declare module.exports: any;
}

declare module 'npm-run/test/exec' {
  declare module.exports: any;
}

declare module 'npm-run/test/spawn' {
  declare module.exports: any;
}

// Filename aliases
declare module 'npm-run/bin/npm-run.js' {
  declare module.exports: $Exports<'npm-run/bin/npm-run'>;
}
declare module 'npm-run/index' {
  declare module.exports: $Exports<'npm-run'>;
}
declare module 'npm-run/index.js' {
  declare module.exports: $Exports<'npm-run'>;
}
declare module 'npm-run/test/bin.js' {
  declare module.exports: $Exports<'npm-run/test/bin'>;
}
declare module 'npm-run/test/exec.js' {
  declare module.exports: $Exports<'npm-run/test/exec'>;
}
declare module 'npm-run/test/spawn.js' {
  declare module.exports: $Exports<'npm-run/test/spawn'>;
}
