// flow-typed signature: 881488519370bfd163021f017d19674a
// flow-typed version: <<STUB>>/pull-delay_v^1.0.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'pull-delay'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'pull-delay' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'pull-delay/index' {
  declare module.exports: $Exports<'pull-delay'>;
}
declare module 'pull-delay/index.js' {
  declare module.exports: $Exports<'pull-delay'>;
}
