// flow-typed signature: f5542d70ffbc2294d359b8ce077eefd5
// flow-typed version: <<STUB>>/snap-shot-core_v^1.2.2/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'snap-shot-core'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'snap-shot-core' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'snap-shot-core/src/browser-system' {
  declare module.exports: any;
}

declare module 'snap-shot-core/src/cypress-system' {
  declare module.exports: any;
}

declare module 'snap-shot-core/src/file-system' {
  declare module.exports: any;
}

declare module 'snap-shot-core/src/index' {
  declare module.exports: any;
}

declare module 'snap-shot-core/src/utils' {
  declare module.exports: any;
}

// Filename aliases
declare module 'snap-shot-core/src/browser-system.js' {
  declare module.exports: $Exports<'snap-shot-core/src/browser-system'>;
}
declare module 'snap-shot-core/src/cypress-system.js' {
  declare module.exports: $Exports<'snap-shot-core/src/cypress-system'>;
}
declare module 'snap-shot-core/src/file-system.js' {
  declare module.exports: $Exports<'snap-shot-core/src/file-system'>;
}
declare module 'snap-shot-core/src/index.js' {
  declare module.exports: $Exports<'snap-shot-core/src/index'>;
}
declare module 'snap-shot-core/src/utils.js' {
  declare module.exports: $Exports<'snap-shot-core/src/utils'>;
}
