// flow-typed signature: 57da19e36d0c31ae54cd80dea279e39d
// flow-typed version: <<STUB>>/yadda_v^1.2.0/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'yadda'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'yadda' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'yadda/bin/browserify' {
  declare module.exports: any;
}

declare module 'yadda/bin/examples' {
  declare module.exports: any;
}

declare module 'yadda/examples/basic-async/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/basic-async/demo' {
  declare module.exports: any;
}

declare module 'yadda/examples/basic-async/lib/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/basic/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/basic/demo' {
  declare module.exports: any;
}

declare module 'yadda/examples/basic/lib/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/casper/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/casper/google-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/casper/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/build/build' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Array' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Competition' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Context' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/date-converter' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/float-converter' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/integer-converter' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/pass-through-converter' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Dictionary' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/EventBus' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/FeatureFileSearch' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/FileSearch' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/fn' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Interpreter' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/LevenshteinDistanceScore' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Library' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/English' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/French' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/German' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Language' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Norwegian' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Pirate' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Polish' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Portuguese' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Russian' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Spanish' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Macro' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/FeatureFileParser' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/FeatureParser' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/StepParser' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Platform' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/CasperPlugin' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/mocha/BasePlugin' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/mocha/ScenarioLevelPlugin' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/mocha/StepLevelPlugin' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/RegularExpression' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/shims/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/StringUtils' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Yadda' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/assertion' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/core/assertions' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/error' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/interface/assert' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/interface/expect' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/interface/should' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/addChainableMethod' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/addMethod' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/addProperty' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/eql' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/flag' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getActual' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getEnumerableProperties' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getMessage' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getName' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getPathValue' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getProperties' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/inspect' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/objDisplay' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/overwriteMethod' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/overwriteProperty' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/transferFlags' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/type' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/features/bottles.feature' {
  declare module.exports: any;
}

declare module 'yadda/examples/component-browser/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/context/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/context/lib/discharge-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/context/lib/hospital-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/context/lib/patient-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/context/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/data-tables/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/data-tables/library' {
  declare module.exports: any;
}

declare module 'yadda/examples/data-tables/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/dictionary/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/dictionary/dictionary-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/dictionary/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/jasmine/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/jasmine/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/jasmine/spec/bottles-spec' {
  declare module.exports: any;
}

declare module 'yadda/examples/localisation/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/localisation/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/localisation/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-async-slp/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-async-slp/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-async-slp/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-async-thenable/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-async-thenable/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-async-thenable/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-async/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-async/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-async/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-express/app' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-express/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-express/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-express/routes/bottles' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-express/routes/server' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-express/test/steps/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-express/test/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-mixed-async-sync/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-mixed-async-sync/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-mixed-async-sync/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-multi-library/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-multi-library/lib/bottle-steps' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-multi-library/lib/common-steps' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-multi-library/lib/dictionary' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-multi-library/lib/vase-steps' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-multi-library/lib/Wall' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-multi-library/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-sync/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-sync/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/mocha-sync/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/multiline-examples-table/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/multiline-examples-table/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/multiline-examples-table/transpile-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/multiline-steps/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/multiline-steps/csv-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/multiline-steps/poem-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/multiline-steps/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/multiline-steps/transpile-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/nightwatch/nightwatch.conf' {
  declare module.exports: any;
}

declare module 'yadda/examples/nightwatch/tests/converters/filter' {
  declare module.exports: any;
}

declare module 'yadda/examples/nightwatch/tests/converters/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/nightwatch/tests/pages/jobsHome' {
  declare module.exports: any;
}

declare module 'yadda/examples/nightwatch/tests/pages/jobsSearch' {
  declare module.exports: any;
}

declare module 'yadda/examples/nightwatch/tests/runner/index' {
  declare module.exports: any;
}

declare module 'yadda/examples/nightwatch/tests/steps/dictionary' {
  declare module.exports: any;
}

declare module 'yadda/examples/nightwatch/tests/steps/jobsHome' {
  declare module.exports: any;
}

declare module 'yadda/examples/nightwatch/tests/steps/jobsSearch' {
  declare module.exports: any;
}

declare module 'yadda/examples/nodeunit/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/nodeunit/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/nodeunit/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/qunit/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/qunit/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/qunit/lib/qunit-1.10.0' {
  declare module.exports: any;
}

declare module 'yadda/examples/report-unused-steps/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/report-unused-steps/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/report-unused-steps/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/resuable-scenarios/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/resuable-scenarios/bottles-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/resuable-scenarios/test' {
  declare module.exports: any;
}

declare module 'yadda/examples/zombie/bin/example' {
  declare module.exports: any;
}

declare module 'yadda/examples/zombie/google-library' {
  declare module.exports: any;
}

declare module 'yadda/examples/zombie/test' {
  declare module.exports: any;
}

declare module 'yadda/karma.conf' {
  declare module.exports: any;
}

declare module 'yadda/lib/Array' {
  declare module.exports: any;
}

declare module 'yadda/lib/Competition' {
  declare module.exports: any;
}

declare module 'yadda/lib/Context' {
  declare module.exports: any;
}

declare module 'yadda/lib/converters/date-converter' {
  declare module.exports: any;
}

declare module 'yadda/lib/converters/float-converter' {
  declare module.exports: any;
}

declare module 'yadda/lib/converters/index' {
  declare module.exports: any;
}

declare module 'yadda/lib/converters/integer-converter' {
  declare module.exports: any;
}

declare module 'yadda/lib/converters/list-converter' {
  declare module.exports: any;
}

declare module 'yadda/lib/converters/pass-through-converter' {
  declare module.exports: any;
}

declare module 'yadda/lib/converters/table-converter' {
  declare module.exports: any;
}

declare module 'yadda/lib/Dictionary' {
  declare module.exports: any;
}

declare module 'yadda/lib/EventBus' {
  declare module.exports: any;
}

declare module 'yadda/lib/FeatureFileSearch' {
  declare module.exports: any;
}

declare module 'yadda/lib/FileSearch' {
  declare module.exports: any;
}

declare module 'yadda/lib/fn' {
  declare module.exports: any;
}

declare module 'yadda/lib/index' {
  declare module.exports: any;
}

declare module 'yadda/lib/Interpreter' {
  declare module.exports: any;
}

declare module 'yadda/lib/Library' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/Chinese' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/Dutch' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/English' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/French' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/German' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/index' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/Language' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/Norwegian' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/Pirate' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/Polish' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/Portuguese' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/Russian' {
  declare module.exports: any;
}

declare module 'yadda/lib/localisation/Spanish' {
  declare module.exports: any;
}

declare module 'yadda/lib/Macro' {
  declare module.exports: any;
}

declare module 'yadda/lib/parsers/FeatureFileParser' {
  declare module.exports: any;
}

declare module 'yadda/lib/parsers/FeatureParser' {
  declare module.exports: any;
}

declare module 'yadda/lib/parsers/index' {
  declare module.exports: any;
}

declare module 'yadda/lib/parsers/StepParser' {
  declare module.exports: any;
}

declare module 'yadda/lib/Platform' {
  declare module.exports: any;
}

declare module 'yadda/lib/plugins/CasperPlugin' {
  declare module.exports: any;
}

declare module 'yadda/lib/plugins/index' {
  declare module.exports: any;
}

declare module 'yadda/lib/plugins/mocha/BasePlugin' {
  declare module.exports: any;
}

declare module 'yadda/lib/plugins/mocha/ScenarioLevelPlugin' {
  declare module.exports: any;
}

declare module 'yadda/lib/plugins/mocha/StepLevelPlugin' {
  declare module.exports: any;
}

declare module 'yadda/lib/RegularExpression' {
  declare module.exports: any;
}

declare module 'yadda/lib/scores/LevenshteinDistanceScore' {
  declare module.exports: any;
}

declare module 'yadda/lib/scores/MultiScore' {
  declare module.exports: any;
}

declare module 'yadda/lib/scores/SameLibraryScore' {
  declare module.exports: any;
}

declare module 'yadda/lib/shims/index' {
  declare module.exports: any;
}

declare module 'yadda/lib/shims/karma-fs' {
  declare module.exports: any;
}

declare module 'yadda/lib/shims/karma-path' {
  declare module.exports: any;
}

declare module 'yadda/lib/shims/karma-process' {
  declare module.exports: any;
}

declare module 'yadda/lib/shims/phantom-fs' {
  declare module.exports: any;
}

declare module 'yadda/lib/shims/phantom-path' {
  declare module.exports: any;
}

declare module 'yadda/lib/shims/phantom-process' {
  declare module.exports: any;
}

declare module 'yadda/lib/StringUtils' {
  declare module.exports: any;
}

declare module 'yadda/lib/Yadda' {
  declare module.exports: any;
}

declare module 'yadda/test/ArrayTests' {
  declare module.exports: any;
}

declare module 'yadda/test/CompetitionTests' {
  declare module.exports: any;
}

declare module 'yadda/test/ContextTests' {
  declare module.exports: any;
}

declare module 'yadda/test/converters/DateConverterTest' {
  declare module.exports: any;
}

declare module 'yadda/test/converters/FloatConverterTest' {
  declare module.exports: any;
}

declare module 'yadda/test/converters/IntegerConverterTest' {
  declare module.exports: any;
}

declare module 'yadda/test/converters/ListConverterTest' {
  declare module.exports: any;
}

declare module 'yadda/test/converters/TableConverterTest' {
  declare module.exports: any;
}

declare module 'yadda/test/Counter' {
  declare module.exports: any;
}

declare module 'yadda/test/DictionaryTests' {
  declare module.exports: any;
}

declare module 'yadda/test/EventBusTests' {
  declare module.exports: any;
}

declare module 'yadda/test/FeatureFileSearchTests' {
  declare module.exports: any;
}

declare module 'yadda/test/FeatureParserTests' {
  declare module.exports: any;
}

declare module 'yadda/test/filesearch/exclude' {
  declare module.exports: any;
}

declare module 'yadda/test/filesearch/subdir1/exclude' {
  declare module.exports: any;
}

declare module 'yadda/test/filesearch/subdir2/subdir3/exclude' {
  declare module.exports: any;
}

declare module 'yadda/test/FileSearchTests' {
  declare module.exports: any;
}

declare module 'yadda/test/FunctionalTests' {
  declare module.exports: any;
}

declare module 'yadda/test/InterpreterTests' {
  declare module.exports: any;
}

declare module 'yadda/test/lib/hospital-steps' {
  declare module.exports: any;
}

declare module 'yadda/test/lib/hospital' {
  declare module.exports: any;
}

declare module 'yadda/test/LibraryTests' {
  declare module.exports: any;
}

declare module 'yadda/test/LocalisationTests' {
  declare module.exports: any;
}

declare module 'yadda/test/MacroTests' {
  declare module.exports: any;
}

declare module 'yadda/test/RegularExpressionTests' {
  declare module.exports: any;
}

declare module 'yadda/test/scores/MultiScoreTests' {
  declare module.exports: any;
}

declare module 'yadda/test/shims/FileSystemTests' {
  declare module.exports: any;
}

declare module 'yadda/test/shims/PathTests' {
  declare module.exports: any;
}

declare module 'yadda/test/shims/ProcessTests' {
  declare module.exports: any;
}

declare module 'yadda/test/StepParserTests' {
  declare module.exports: any;
}

declare module 'yadda/test/StringUtilsTests' {
  declare module.exports: any;
}

declare module 'yadda/test/YaddaTests' {
  declare module.exports: any;
}

// Filename aliases
declare module 'yadda/bin/browserify.js' {
  declare module.exports: $Exports<'yadda/bin/browserify'>;
}
declare module 'yadda/bin/examples.js' {
  declare module.exports: $Exports<'yadda/bin/examples'>;
}
declare module 'yadda/examples/basic-async/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/basic-async/bin/example'>;
}
declare module 'yadda/examples/basic-async/demo.js' {
  declare module.exports: $Exports<'yadda/examples/basic-async/demo'>;
}
declare module 'yadda/examples/basic-async/lib/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/basic-async/lib/bottles-library'>;
}
declare module 'yadda/examples/basic/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/basic/bin/example'>;
}
declare module 'yadda/examples/basic/demo.js' {
  declare module.exports: $Exports<'yadda/examples/basic/demo'>;
}
declare module 'yadda/examples/basic/lib/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/basic/lib/bottles-library'>;
}
declare module 'yadda/examples/casper/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/casper/bin/example'>;
}
declare module 'yadda/examples/casper/google-library.js' {
  declare module.exports: $Exports<'yadda/examples/casper/google-library'>;
}
declare module 'yadda/examples/casper/test.js' {
  declare module.exports: $Exports<'yadda/examples/casper/test'>;
}
declare module 'yadda/examples/component-browser/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/bin/example'>;
}
declare module 'yadda/examples/component-browser/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/bottles-library'>;
}
declare module 'yadda/examples/component-browser/build/build.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/build/build'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Array.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/Array'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Competition.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/Competition'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Context.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/Context'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/date-converter.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/date-converter'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/float-converter.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/float-converter'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/index.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/index'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/integer-converter.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/integer-converter'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/pass-through-converter.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/converters/pass-through-converter'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Dictionary.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/Dictionary'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/EventBus.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/EventBus'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/FeatureFileSearch.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/FeatureFileSearch'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/FileSearch.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/FileSearch'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/fn.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/fn'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/index.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/index'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Interpreter.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/Interpreter'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/LevenshteinDistanceScore.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/LevenshteinDistanceScore'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Library.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/Library'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/English.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/English'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/French.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/French'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/German.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/German'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/index.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/index'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Language.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Language'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Norwegian.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Norwegian'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Pirate.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Pirate'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Polish.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Polish'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Portuguese.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Portuguese'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Russian.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Russian'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Spanish.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/localisation/Spanish'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Macro.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/Macro'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/FeatureFileParser.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/FeatureFileParser'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/FeatureParser.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/FeatureParser'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/index.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/index'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/StepParser.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/parsers/StepParser'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Platform.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/Platform'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/CasperPlugin.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/CasperPlugin'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/index.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/index'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/mocha/BasePlugin.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/mocha/BasePlugin'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/mocha/ScenarioLevelPlugin.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/mocha/ScenarioLevelPlugin'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/mocha/StepLevelPlugin.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/plugins/mocha/StepLevelPlugin'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/RegularExpression.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/RegularExpression'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/shims/index.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/shims/index'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/StringUtils.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/StringUtils'>;
}
declare module 'yadda/examples/component-browser/components/acuminous-yadda/lib/Yadda.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/acuminous-yadda/lib/Yadda'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/index.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/index'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/assertion.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/assertion'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/core/assertions.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/core/assertions'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/error.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/error'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/interface/assert.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/interface/assert'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/interface/expect.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/interface/expect'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/interface/should.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/interface/should'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/addChainableMethod.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/addChainableMethod'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/addMethod.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/addMethod'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/addProperty.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/addProperty'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/eql.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/eql'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/flag.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/flag'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getActual.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getActual'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getEnumerableProperties.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getEnumerableProperties'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getMessage.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getMessage'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getName.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getName'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getPathValue.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getPathValue'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getProperties.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/getProperties'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/index.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/index'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/inspect.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/inspect'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/objDisplay.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/objDisplay'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/overwriteMethod.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/overwriteMethod'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/overwriteProperty.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/overwriteProperty'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/test.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/test'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/transferFlags.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/transferFlags'>;
}
declare module 'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/type.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/components/chaijs-chai/lib/chai/utils/type'>;
}
declare module 'yadda/examples/component-browser/features/bottles.feature.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/features/bottles.feature'>;
}
declare module 'yadda/examples/component-browser/test.js' {
  declare module.exports: $Exports<'yadda/examples/component-browser/test'>;
}
declare module 'yadda/examples/context/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/context/bin/example'>;
}
declare module 'yadda/examples/context/lib/discharge-library.js' {
  declare module.exports: $Exports<'yadda/examples/context/lib/discharge-library'>;
}
declare module 'yadda/examples/context/lib/hospital-library.js' {
  declare module.exports: $Exports<'yadda/examples/context/lib/hospital-library'>;
}
declare module 'yadda/examples/context/lib/patient-library.js' {
  declare module.exports: $Exports<'yadda/examples/context/lib/patient-library'>;
}
declare module 'yadda/examples/context/test.js' {
  declare module.exports: $Exports<'yadda/examples/context/test'>;
}
declare module 'yadda/examples/data-tables/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/data-tables/bin/example'>;
}
declare module 'yadda/examples/data-tables/library.js' {
  declare module.exports: $Exports<'yadda/examples/data-tables/library'>;
}
declare module 'yadda/examples/data-tables/test.js' {
  declare module.exports: $Exports<'yadda/examples/data-tables/test'>;
}
declare module 'yadda/examples/dictionary/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/dictionary/bin/example'>;
}
declare module 'yadda/examples/dictionary/dictionary-library.js' {
  declare module.exports: $Exports<'yadda/examples/dictionary/dictionary-library'>;
}
declare module 'yadda/examples/dictionary/test.js' {
  declare module.exports: $Exports<'yadda/examples/dictionary/test'>;
}
declare module 'yadda/examples/jasmine/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/jasmine/bin/example'>;
}
declare module 'yadda/examples/jasmine/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/jasmine/bottles-library'>;
}
declare module 'yadda/examples/jasmine/spec/bottles-spec.js' {
  declare module.exports: $Exports<'yadda/examples/jasmine/spec/bottles-spec'>;
}
declare module 'yadda/examples/localisation/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/localisation/bin/example'>;
}
declare module 'yadda/examples/localisation/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/localisation/bottles-library'>;
}
declare module 'yadda/examples/localisation/test.js' {
  declare module.exports: $Exports<'yadda/examples/localisation/test'>;
}
declare module 'yadda/examples/mocha-async-slp/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-async-slp/bin/example'>;
}
declare module 'yadda/examples/mocha-async-slp/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-async-slp/bottles-library'>;
}
declare module 'yadda/examples/mocha-async-slp/test.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-async-slp/test'>;
}
declare module 'yadda/examples/mocha-async-thenable/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-async-thenable/bin/example'>;
}
declare module 'yadda/examples/mocha-async-thenable/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-async-thenable/bottles-library'>;
}
declare module 'yadda/examples/mocha-async-thenable/test.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-async-thenable/test'>;
}
declare module 'yadda/examples/mocha-async/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-async/bin/example'>;
}
declare module 'yadda/examples/mocha-async/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-async/bottles-library'>;
}
declare module 'yadda/examples/mocha-async/test.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-async/test'>;
}
declare module 'yadda/examples/mocha-express/app.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-express/app'>;
}
declare module 'yadda/examples/mocha-express/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-express/bin/example'>;
}
declare module 'yadda/examples/mocha-express/index.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-express/index'>;
}
declare module 'yadda/examples/mocha-express/routes/bottles.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-express/routes/bottles'>;
}
declare module 'yadda/examples/mocha-express/routes/server.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-express/routes/server'>;
}
declare module 'yadda/examples/mocha-express/test/steps/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-express/test/steps/bottles-library'>;
}
declare module 'yadda/examples/mocha-express/test/test.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-express/test/test'>;
}
declare module 'yadda/examples/mocha-mixed-async-sync/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-mixed-async-sync/bin/example'>;
}
declare module 'yadda/examples/mocha-mixed-async-sync/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-mixed-async-sync/bottles-library'>;
}
declare module 'yadda/examples/mocha-mixed-async-sync/test.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-mixed-async-sync/test'>;
}
declare module 'yadda/examples/mocha-multi-library/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-multi-library/bin/example'>;
}
declare module 'yadda/examples/mocha-multi-library/lib/bottle-steps.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-multi-library/lib/bottle-steps'>;
}
declare module 'yadda/examples/mocha-multi-library/lib/common-steps.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-multi-library/lib/common-steps'>;
}
declare module 'yadda/examples/mocha-multi-library/lib/dictionary.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-multi-library/lib/dictionary'>;
}
declare module 'yadda/examples/mocha-multi-library/lib/vase-steps.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-multi-library/lib/vase-steps'>;
}
declare module 'yadda/examples/mocha-multi-library/lib/Wall.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-multi-library/lib/Wall'>;
}
declare module 'yadda/examples/mocha-multi-library/test.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-multi-library/test'>;
}
declare module 'yadda/examples/mocha-sync/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-sync/bin/example'>;
}
declare module 'yadda/examples/mocha-sync/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-sync/bottles-library'>;
}
declare module 'yadda/examples/mocha-sync/test.js' {
  declare module.exports: $Exports<'yadda/examples/mocha-sync/test'>;
}
declare module 'yadda/examples/multiline-examples-table/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/multiline-examples-table/bin/example'>;
}
declare module 'yadda/examples/multiline-examples-table/test.js' {
  declare module.exports: $Exports<'yadda/examples/multiline-examples-table/test'>;
}
declare module 'yadda/examples/multiline-examples-table/transpile-library.js' {
  declare module.exports: $Exports<'yadda/examples/multiline-examples-table/transpile-library'>;
}
declare module 'yadda/examples/multiline-steps/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/multiline-steps/bin/example'>;
}
declare module 'yadda/examples/multiline-steps/csv-library.js' {
  declare module.exports: $Exports<'yadda/examples/multiline-steps/csv-library'>;
}
declare module 'yadda/examples/multiline-steps/poem-library.js' {
  declare module.exports: $Exports<'yadda/examples/multiline-steps/poem-library'>;
}
declare module 'yadda/examples/multiline-steps/test.js' {
  declare module.exports: $Exports<'yadda/examples/multiline-steps/test'>;
}
declare module 'yadda/examples/multiline-steps/transpile-library.js' {
  declare module.exports: $Exports<'yadda/examples/multiline-steps/transpile-library'>;
}
declare module 'yadda/examples/nightwatch/nightwatch.conf.js' {
  declare module.exports: $Exports<'yadda/examples/nightwatch/nightwatch.conf'>;
}
declare module 'yadda/examples/nightwatch/tests/converters/filter.js' {
  declare module.exports: $Exports<'yadda/examples/nightwatch/tests/converters/filter'>;
}
declare module 'yadda/examples/nightwatch/tests/converters/index.js' {
  declare module.exports: $Exports<'yadda/examples/nightwatch/tests/converters/index'>;
}
declare module 'yadda/examples/nightwatch/tests/pages/jobsHome.js' {
  declare module.exports: $Exports<'yadda/examples/nightwatch/tests/pages/jobsHome'>;
}
declare module 'yadda/examples/nightwatch/tests/pages/jobsSearch.js' {
  declare module.exports: $Exports<'yadda/examples/nightwatch/tests/pages/jobsSearch'>;
}
declare module 'yadda/examples/nightwatch/tests/runner/index.js' {
  declare module.exports: $Exports<'yadda/examples/nightwatch/tests/runner/index'>;
}
declare module 'yadda/examples/nightwatch/tests/steps/dictionary.js' {
  declare module.exports: $Exports<'yadda/examples/nightwatch/tests/steps/dictionary'>;
}
declare module 'yadda/examples/nightwatch/tests/steps/jobsHome.js' {
  declare module.exports: $Exports<'yadda/examples/nightwatch/tests/steps/jobsHome'>;
}
declare module 'yadda/examples/nightwatch/tests/steps/jobsSearch.js' {
  declare module.exports: $Exports<'yadda/examples/nightwatch/tests/steps/jobsSearch'>;
}
declare module 'yadda/examples/nodeunit/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/nodeunit/bin/example'>;
}
declare module 'yadda/examples/nodeunit/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/nodeunit/bottles-library'>;
}
declare module 'yadda/examples/nodeunit/test.js' {
  declare module.exports: $Exports<'yadda/examples/nodeunit/test'>;
}
declare module 'yadda/examples/qunit/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/qunit/bin/example'>;
}
declare module 'yadda/examples/qunit/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/qunit/bottles-library'>;
}
declare module 'yadda/examples/qunit/lib/qunit-1.10.0.js' {
  declare module.exports: $Exports<'yadda/examples/qunit/lib/qunit-1.10.0'>;
}
declare module 'yadda/examples/report-unused-steps/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/report-unused-steps/bin/example'>;
}
declare module 'yadda/examples/report-unused-steps/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/report-unused-steps/bottles-library'>;
}
declare module 'yadda/examples/report-unused-steps/test.js' {
  declare module.exports: $Exports<'yadda/examples/report-unused-steps/test'>;
}
declare module 'yadda/examples/resuable-scenarios/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/resuable-scenarios/bin/example'>;
}
declare module 'yadda/examples/resuable-scenarios/bottles-library.js' {
  declare module.exports: $Exports<'yadda/examples/resuable-scenarios/bottles-library'>;
}
declare module 'yadda/examples/resuable-scenarios/test.js' {
  declare module.exports: $Exports<'yadda/examples/resuable-scenarios/test'>;
}
declare module 'yadda/examples/zombie/bin/example.js' {
  declare module.exports: $Exports<'yadda/examples/zombie/bin/example'>;
}
declare module 'yadda/examples/zombie/google-library.js' {
  declare module.exports: $Exports<'yadda/examples/zombie/google-library'>;
}
declare module 'yadda/examples/zombie/test.js' {
  declare module.exports: $Exports<'yadda/examples/zombie/test'>;
}
declare module 'yadda/karma.conf.js' {
  declare module.exports: $Exports<'yadda/karma.conf'>;
}
declare module 'yadda/lib/Array.js' {
  declare module.exports: $Exports<'yadda/lib/Array'>;
}
declare module 'yadda/lib/Competition.js' {
  declare module.exports: $Exports<'yadda/lib/Competition'>;
}
declare module 'yadda/lib/Context.js' {
  declare module.exports: $Exports<'yadda/lib/Context'>;
}
declare module 'yadda/lib/converters/date-converter.js' {
  declare module.exports: $Exports<'yadda/lib/converters/date-converter'>;
}
declare module 'yadda/lib/converters/float-converter.js' {
  declare module.exports: $Exports<'yadda/lib/converters/float-converter'>;
}
declare module 'yadda/lib/converters/index.js' {
  declare module.exports: $Exports<'yadda/lib/converters/index'>;
}
declare module 'yadda/lib/converters/integer-converter.js' {
  declare module.exports: $Exports<'yadda/lib/converters/integer-converter'>;
}
declare module 'yadda/lib/converters/list-converter.js' {
  declare module.exports: $Exports<'yadda/lib/converters/list-converter'>;
}
declare module 'yadda/lib/converters/pass-through-converter.js' {
  declare module.exports: $Exports<'yadda/lib/converters/pass-through-converter'>;
}
declare module 'yadda/lib/converters/table-converter.js' {
  declare module.exports: $Exports<'yadda/lib/converters/table-converter'>;
}
declare module 'yadda/lib/Dictionary.js' {
  declare module.exports: $Exports<'yadda/lib/Dictionary'>;
}
declare module 'yadda/lib/EventBus.js' {
  declare module.exports: $Exports<'yadda/lib/EventBus'>;
}
declare module 'yadda/lib/FeatureFileSearch.js' {
  declare module.exports: $Exports<'yadda/lib/FeatureFileSearch'>;
}
declare module 'yadda/lib/FileSearch.js' {
  declare module.exports: $Exports<'yadda/lib/FileSearch'>;
}
declare module 'yadda/lib/fn.js' {
  declare module.exports: $Exports<'yadda/lib/fn'>;
}
declare module 'yadda/lib/index.js' {
  declare module.exports: $Exports<'yadda/lib/index'>;
}
declare module 'yadda/lib/Interpreter.js' {
  declare module.exports: $Exports<'yadda/lib/Interpreter'>;
}
declare module 'yadda/lib/Library.js' {
  declare module.exports: $Exports<'yadda/lib/Library'>;
}
declare module 'yadda/lib/localisation/Chinese.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/Chinese'>;
}
declare module 'yadda/lib/localisation/Dutch.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/Dutch'>;
}
declare module 'yadda/lib/localisation/English.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/English'>;
}
declare module 'yadda/lib/localisation/French.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/French'>;
}
declare module 'yadda/lib/localisation/German.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/German'>;
}
declare module 'yadda/lib/localisation/index.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/index'>;
}
declare module 'yadda/lib/localisation/Language.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/Language'>;
}
declare module 'yadda/lib/localisation/Norwegian.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/Norwegian'>;
}
declare module 'yadda/lib/localisation/Pirate.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/Pirate'>;
}
declare module 'yadda/lib/localisation/Polish.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/Polish'>;
}
declare module 'yadda/lib/localisation/Portuguese.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/Portuguese'>;
}
declare module 'yadda/lib/localisation/Russian.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/Russian'>;
}
declare module 'yadda/lib/localisation/Spanish.js' {
  declare module.exports: $Exports<'yadda/lib/localisation/Spanish'>;
}
declare module 'yadda/lib/Macro.js' {
  declare module.exports: $Exports<'yadda/lib/Macro'>;
}
declare module 'yadda/lib/parsers/FeatureFileParser.js' {
  declare module.exports: $Exports<'yadda/lib/parsers/FeatureFileParser'>;
}
declare module 'yadda/lib/parsers/FeatureParser.js' {
  declare module.exports: $Exports<'yadda/lib/parsers/FeatureParser'>;
}
declare module 'yadda/lib/parsers/index.js' {
  declare module.exports: $Exports<'yadda/lib/parsers/index'>;
}
declare module 'yadda/lib/parsers/StepParser.js' {
  declare module.exports: $Exports<'yadda/lib/parsers/StepParser'>;
}
declare module 'yadda/lib/Platform.js' {
  declare module.exports: $Exports<'yadda/lib/Platform'>;
}
declare module 'yadda/lib/plugins/CasperPlugin.js' {
  declare module.exports: $Exports<'yadda/lib/plugins/CasperPlugin'>;
}
declare module 'yadda/lib/plugins/index.js' {
  declare module.exports: $Exports<'yadda/lib/plugins/index'>;
}
declare module 'yadda/lib/plugins/mocha/BasePlugin.js' {
  declare module.exports: $Exports<'yadda/lib/plugins/mocha/BasePlugin'>;
}
declare module 'yadda/lib/plugins/mocha/ScenarioLevelPlugin.js' {
  declare module.exports: $Exports<'yadda/lib/plugins/mocha/ScenarioLevelPlugin'>;
}
declare module 'yadda/lib/plugins/mocha/StepLevelPlugin.js' {
  declare module.exports: $Exports<'yadda/lib/plugins/mocha/StepLevelPlugin'>;
}
declare module 'yadda/lib/RegularExpression.js' {
  declare module.exports: $Exports<'yadda/lib/RegularExpression'>;
}
declare module 'yadda/lib/scores/LevenshteinDistanceScore.js' {
  declare module.exports: $Exports<'yadda/lib/scores/LevenshteinDistanceScore'>;
}
declare module 'yadda/lib/scores/MultiScore.js' {
  declare module.exports: $Exports<'yadda/lib/scores/MultiScore'>;
}
declare module 'yadda/lib/scores/SameLibraryScore.js' {
  declare module.exports: $Exports<'yadda/lib/scores/SameLibraryScore'>;
}
declare module 'yadda/lib/shims/index.js' {
  declare module.exports: $Exports<'yadda/lib/shims/index'>;
}
declare module 'yadda/lib/shims/karma-fs.js' {
  declare module.exports: $Exports<'yadda/lib/shims/karma-fs'>;
}
declare module 'yadda/lib/shims/karma-path.js' {
  declare module.exports: $Exports<'yadda/lib/shims/karma-path'>;
}
declare module 'yadda/lib/shims/karma-process.js' {
  declare module.exports: $Exports<'yadda/lib/shims/karma-process'>;
}
declare module 'yadda/lib/shims/phantom-fs.js' {
  declare module.exports: $Exports<'yadda/lib/shims/phantom-fs'>;
}
declare module 'yadda/lib/shims/phantom-path.js' {
  declare module.exports: $Exports<'yadda/lib/shims/phantom-path'>;
}
declare module 'yadda/lib/shims/phantom-process.js' {
  declare module.exports: $Exports<'yadda/lib/shims/phantom-process'>;
}
declare module 'yadda/lib/StringUtils.js' {
  declare module.exports: $Exports<'yadda/lib/StringUtils'>;
}
declare module 'yadda/lib/Yadda.js' {
  declare module.exports: $Exports<'yadda/lib/Yadda'>;
}
declare module 'yadda/test/ArrayTests.js' {
  declare module.exports: $Exports<'yadda/test/ArrayTests'>;
}
declare module 'yadda/test/CompetitionTests.js' {
  declare module.exports: $Exports<'yadda/test/CompetitionTests'>;
}
declare module 'yadda/test/ContextTests.js' {
  declare module.exports: $Exports<'yadda/test/ContextTests'>;
}
declare module 'yadda/test/converters/DateConverterTest.js' {
  declare module.exports: $Exports<'yadda/test/converters/DateConverterTest'>;
}
declare module 'yadda/test/converters/FloatConverterTest.js' {
  declare module.exports: $Exports<'yadda/test/converters/FloatConverterTest'>;
}
declare module 'yadda/test/converters/IntegerConverterTest.js' {
  declare module.exports: $Exports<'yadda/test/converters/IntegerConverterTest'>;
}
declare module 'yadda/test/converters/ListConverterTest.js' {
  declare module.exports: $Exports<'yadda/test/converters/ListConverterTest'>;
}
declare module 'yadda/test/converters/TableConverterTest.js' {
  declare module.exports: $Exports<'yadda/test/converters/TableConverterTest'>;
}
declare module 'yadda/test/Counter.js' {
  declare module.exports: $Exports<'yadda/test/Counter'>;
}
declare module 'yadda/test/DictionaryTests.js' {
  declare module.exports: $Exports<'yadda/test/DictionaryTests'>;
}
declare module 'yadda/test/EventBusTests.js' {
  declare module.exports: $Exports<'yadda/test/EventBusTests'>;
}
declare module 'yadda/test/FeatureFileSearchTests.js' {
  declare module.exports: $Exports<'yadda/test/FeatureFileSearchTests'>;
}
declare module 'yadda/test/FeatureParserTests.js' {
  declare module.exports: $Exports<'yadda/test/FeatureParserTests'>;
}
declare module 'yadda/test/filesearch/exclude.js' {
  declare module.exports: $Exports<'yadda/test/filesearch/exclude'>;
}
declare module 'yadda/test/filesearch/subdir1/exclude.js' {
  declare module.exports: $Exports<'yadda/test/filesearch/subdir1/exclude'>;
}
declare module 'yadda/test/filesearch/subdir2/subdir3/exclude.js' {
  declare module.exports: $Exports<'yadda/test/filesearch/subdir2/subdir3/exclude'>;
}
declare module 'yadda/test/FileSearchTests.js' {
  declare module.exports: $Exports<'yadda/test/FileSearchTests'>;
}
declare module 'yadda/test/FunctionalTests.js' {
  declare module.exports: $Exports<'yadda/test/FunctionalTests'>;
}
declare module 'yadda/test/InterpreterTests.js' {
  declare module.exports: $Exports<'yadda/test/InterpreterTests'>;
}
declare module 'yadda/test/lib/hospital-steps.js' {
  declare module.exports: $Exports<'yadda/test/lib/hospital-steps'>;
}
declare module 'yadda/test/lib/hospital.js' {
  declare module.exports: $Exports<'yadda/test/lib/hospital'>;
}
declare module 'yadda/test/LibraryTests.js' {
  declare module.exports: $Exports<'yadda/test/LibraryTests'>;
}
declare module 'yadda/test/LocalisationTests.js' {
  declare module.exports: $Exports<'yadda/test/LocalisationTests'>;
}
declare module 'yadda/test/MacroTests.js' {
  declare module.exports: $Exports<'yadda/test/MacroTests'>;
}
declare module 'yadda/test/RegularExpressionTests.js' {
  declare module.exports: $Exports<'yadda/test/RegularExpressionTests'>;
}
declare module 'yadda/test/scores/MultiScoreTests.js' {
  declare module.exports: $Exports<'yadda/test/scores/MultiScoreTests'>;
}
declare module 'yadda/test/shims/FileSystemTests.js' {
  declare module.exports: $Exports<'yadda/test/shims/FileSystemTests'>;
}
declare module 'yadda/test/shims/PathTests.js' {
  declare module.exports: $Exports<'yadda/test/shims/PathTests'>;
}
declare module 'yadda/test/shims/ProcessTests.js' {
  declare module.exports: $Exports<'yadda/test/shims/ProcessTests'>;
}
declare module 'yadda/test/StepParserTests.js' {
  declare module.exports: $Exports<'yadda/test/StepParserTests'>;
}
declare module 'yadda/test/StringUtilsTests.js' {
  declare module.exports: $Exports<'yadda/test/StringUtilsTests'>;
}
declare module 'yadda/test/YaddaTests.js' {
  declare module.exports: $Exports<'yadda/test/YaddaTests'>;
}
