// flow-typed signature: 6cda1e6259abac51ec441a5f5bf981b9
// flow-typed version: <<STUB>>/@google-cloud/datastore_v^0.7.1/flow_v0.42.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   '@google-cloud/datastore'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module '@google-cloud/datastore' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module '@google-cloud/datastore/src/entity' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/index' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/query' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/request' {
  declare module.exports: any;
}

declare module '@google-cloud/datastore/src/transaction' {
  declare module.exports: any;
}

// Filename aliases
declare module '@google-cloud/datastore/src/entity.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/entity'>;
}
declare module '@google-cloud/datastore/src/index.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/index'>;
}
declare module '@google-cloud/datastore/src/query.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/query'>;
}
declare module '@google-cloud/datastore/src/request.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/request'>;
}
declare module '@google-cloud/datastore/src/transaction.js' {
  declare module.exports: $Exports<'@google-cloud/datastore/src/transaction'>;
}
